[project]
name = "qcworkflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chemcloud>=0.13.2",
    "jupyterlab>=4.3.5",
    "qcio[all]>=0.13.1",
    "qcop>=0.9.6",
]
